resource_types:
  - name: git
    type: docker-image
    source:
      repository: concourse/git-resource
      tag: 1.3.0
resources:
  - name: git-repo
    type: git
    source:
      uri: {{GIT_REPO}}
      branch: master
  - name: deploy-app-ui
    type: cf
    source:
      api: {{PCF_API}}
      username: {{PCF_USER}}
      password: {{PCF_PASS}}
      organization: {{PCF_ORG}}
      space: {{PCF_SPACE}}
      skip_cert_check: true

jobs:
  - name: app-ui
    serial: true
    plan:
      - get: git-repo
        trigger: true
      - task: build-app-ui
        file: git-repo/concourse/tasks/build-artifact_ui.yml
      - put: deploy-app-ui
        params:
          manifest: app-ui-dist/manifest.yml
          current_app_name: app-ui
          path: app-ui-dist/
