---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"


inputs:
  - name: git-repo
#  - name: version

outputs:
  - name: app-ui-dist

run:
  path: git-repo/ci/scripts/build-artifact_ui.sh

params:
  base_name:
